export const NEXT_PICT = 'NEXT_PICT';
export const PREV_PICT = 'PREV_PICT';
export const TOGGLE_SLIDESHOW = 'TOGGLE_SLIDESHOW';
export const TOGGLE_LIGHTBOX = 'TOGGLE_LIGHTBOX';
export const TOGGLE_PICT_INFO = 'TOGGLE_PICT_INFO';

