# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('content', models.TextField(null=True, verbose_name='Description')),
                ('source', models.TextField(null=True, verbose_name='Source')),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last update date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_update'],
                'get_latest_by': 'date_update',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('mail', models.EmailField(max_length=254, verbose_name='Mail')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('subject', models.CharField(max_length=254, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('forward', models.BooleanField(default=True, verbose_name='Forward')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Send date')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
