# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librairy', '0002_auto_20171008_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('slug', models.CharField(db_index=True, max_length=270, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('slug', models.CharField(db_index=True, max_length=270, unique=True)),
                ('draft', models.BooleanField(db_index=True, default=False, verbose_name='Draft')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('pub_date', models.DateTimeField(blank=True, db_index=True, verbose_name='Publication date')),
                ('order', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.Folder')),
            ],
            options={
                'ordering': ['order', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairy.Picture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Folder')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(blank=True, through='galleries.GalleryPicture', to='librairy.Picture', verbose_name='Pictures'),
        ),
        migrations.AlterUniqueTogether(
            name='gallerypicture',
            unique_together=set([('gallery', 'picture')]),
        ),
    ]
