# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collectionsensemble',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
