# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0008_auto_20151207_1257'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collectionsensemble',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='directory',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
