# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0009_auto_20151215_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='directory',
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
