# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0011_default_collection_ensemble_20160317_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='ensemble',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='librairy.CollectionsEnsemble'),
        ),
        migrations.AlterField(
            model_name='collectionsensemble',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='librairy.CollectionsEnsemble'),
        ),
    ]
