# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0012_auto_20160317_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='ensemble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librairy.CollectionsEnsemble'),
        ),
    ]
