# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0013_auto_20160319_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionsensemble',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
