# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0014_auto_20160323_0657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set([('slug', 'ensemble')]),
        ),
    ]
