# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0015_auto_20160323_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='collection_pictures',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collection_pictures',
            name='picture',
        ),
        migrations.AlterField(
            model_name='collection',
            name='pictures',
            field=models.ManyToManyField(blank=True, through='librairy.CollectionPicture', to='librairy.Picture', verbose_name='Pictures'),
        ),
        migrations.DeleteModel(
            name='Collection_pictures',
        ),
        migrations.AddField(
            model_name='collectionpicture',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairy.Collection'),
        ),
        migrations.AddField(
            model_name='collectionpicture',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairy.Picture'),
        ),
    ]
