# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0016_auto_20160323_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionpicture',
            unique_together=set([('collection', 'picture')]),
        ),
    ]
