# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0017_auto_20160323_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionpicture',
            options={'ordering': ['order']},
        ),
    ]
