# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0018_auto_20160323_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='id',
        ),
        migrations.AlterField(
            model_name='picture',
            name='sha1',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
