# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactHits',
            new_name='ContactHit',
        ),
        migrations.RenameModel(
            old_name='PictureHits',
            new_name='PictureHit',
        ),
        migrations.RenameModel(
            old_name='PortfolioHits',
            new_name='PortfolioHit',
        ),
        migrations.RenameModel(
            old_name='PostHits',
            new_name='PostHit',
        ),
    ]
