# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160611_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacthit',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='picturehit',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='portfoliohit',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='posthit',
            name='staff',
        ),
    ]
