# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_auto_20160611_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=39)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PICT', 'Picture'), ('PORT', 'Portfolio'), ('POST', 'Weblog post'), ('CONTACT', 'Contact')], db_index=True, max_length=40)),
                ('related_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacthit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picturehit',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='picturehit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfoliohit',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliohit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posthit',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posthit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactHit',
        ),
        migrations.DeleteModel(
            name='PictureHit',
        ),
        migrations.DeleteModel(
            name='PortfolioHit',
        ),
        migrations.DeleteModel(
            name='PostHit',
        ),
    ]
