# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160612_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='request_ip',
            field=models.CharField(default=1, max_length=39),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hit',
            name='ip',
            field=models.CharField(db_index=True, max_length=39, null=True),
        ),
    ]
