# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_auto_20150623_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postpicture',
            unique_together=set([('post', 'picture')]),
        ),
    ]
