# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insta_link',
            field=models.URLField(blank=True, help_text='A link to your instagram page', max_length=2000, null=True, verbose_name='Instagram'),
        ),
    ]
