# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.URLField(blank=True, help_text='A link to your blog', max_length=2000, null=True, verbose_name='Blog'),
        ),
    ]
