# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20151206_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_librairy_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_weblog_author',
            field=models.BooleanField(default=False),
        ),
    ]
