# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blog',
            new_name='blog_link',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='website',
            new_name='website_link',
        ),
        migrations.AddField(
            model_name='user',
            name='etsy_link',
            field=models.URLField(blank=True, help_text='A link to etsy page', max_length=2000, null=True, verbose_name='Etsy'),
        ),
    ]
