# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20151215_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validated_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Validated email'),
        ),
    ]
