


/*
 * Portfolios actions
 */
export const REQUEST_PORTFOLIO = 'REQUEST_PORTFOLIO'
export const REQUEST_PORTFOLIO_FAILURE = 'REQUEST_PORTFOLIO_FAILURE'
export const REQUEST_PORTFOLIO_SUCCESS = 'REQUEST_PORTFOLIO_SUCCESS'


export const SELECT_PORTFOLIO = 'SELECT_PORTFOLIO';
export const PORTFOLIO_NEXT_PICT = 'PORTFOLIO_NEXT_PICT';
export const PORTFOLIO_PREV_PICT = 'PORTFOLIO_PREV_PICT';
export const PORTFOLIO_TOGGLE_SLIDESHOW = 'PORTFOLIO_TOGGLE_SLIDESHOW';
export const TOGGLE_LIGHTBOX = 'TOGGLE_LIGHTBOX';
export const TOGGLE_PICT_INFO = 'TOGGLE_PICT_INFO';


/*
 * Viewport actions
 */
export const SET_VIEWPORT = 'SET_VIEWPORT';

