


/*
 * Portfolios actions
 */
export const REQUEST_PORTFOLIOS_HEADERS = 'REQUEST_PORTFOLIOS_HEADERS'
export const REQUEST_PORTFOLIOS_HEADERS_FAILURE = 'REQUEST_PORTFOLIOS_HEADERS_FAILURE'
export const REQUEST_PORTFOLIOS_HEADERS_SUCCESS = 'REQUEST_PORTFOLIOS_HEADERS_SUCCESS'

export const REQUEST_PORTFOLIO = 'REQUEST_PORTFOLIO'
export const REQUEST_PORTFOLIO_FAILURE = 'REQUEST_PORTFOLIO_FAILURE'
export const REQUEST_PORTFOLIO_SUCCESS = 'REQUEST_PORTFOLIO_SUCCESS'

export const REQUEST_PORTFOLIO_PICTURES = 'REQUEST_PORTFOLIO_PICTURES'
export const REQUEST_PORTFOLIO_PICTURES_FAILURE = 'REQUEST_PORTFOLIO_PICTURES_FAILURE'
export const REQUEST_PORTFOLIO_PICTURES_SUCCESS = 'REQUEST_PORTFOLIO_PICTURES_SUCCESS'

export const INVALIDATE_PORTFOLIO = 'INVALIDATE_PORTFOLIO'
export const SELECT_PORTFOLIO = 'SELECT_PORTFOLIO'

export const PORTFOLIO_NEXT_PICT = 'PORTFOLIO_NEXT_PICT'
export const PORTFOLIO_PREV_PICT = 'PORTFOLIO_PREV_PICT'
export const PORTFOLIO_TOGGLE_SLIDESHOW = 'PORTFOLIO_TOGGLE_SLIDESHOW'

export const TOGGLE_LIGHTBOX = 'TOGGLE_LIGHTBOX'
export const TOGGLE_PICT_INFO = 'TOGGLE_PICT_INFO'



/*
 * Pictures actions
 */
export const REQUEST_SHORT_PICTURE = 'REQUEST_SHORT_PICTURE'
export const REQUEST_SHORT_PICTURE_FAILURE = 'REQUEST_SHORT_PICTURE_FAILURE'
export const REQUEST_SHORT_PICTURE_SUCCESS = 'REQUEST_SHORT_PICTURE_SUCCESS'


export const REQUEST_PICTURE = 'REQUEST_PICTURE'
export const REQUEST_PICTURE_FAILURE = 'REQUEST_PICTURE_FAILURE'
export const REQUEST_PICTURE_SUCCESS = 'REQUEST_PICTURE_SUCCESS'



/*
 * Viewport actions
 */
export const SET_VIEWPORT = 'SET_VIEWPORT'


/*
 * Modules actions
 */


/*
 * Contact actions
 */

/*
 * Weblog actions
 */

/*
 * Librairy actions
 */

/*
 * User actions
 */

