# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('slug', models.CharField(db_index=True, max_length=270, unique=True)),
                ('draft', models.BooleanField(db_index=True, default=False, verbose_name='Draft')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('pub_date', models.DateTimeField(blank=True, db_index=True, verbose_name='Publication date')),
                ('order', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librairy.Picture')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pictures',
            field=models.ManyToManyField(blank=True, through='portfolio.PortfolioPicture', to='librairy.Picture', verbose_name='Pictures'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliopicture',
            unique_together=set([('portfolio', 'picture')]),
        ),
    ]
