# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='etsy_link',
            field=models.URLField(blank=True, help_text='Url to a etsy shop, will be displayed                     under a small logo.', null=True, verbose_name='Etsy shop link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='fb_link',
            field=models.URLField(blank=True, help_text='Url to a facebook page, will be displayed                     under a small logo.', null=True, verbose_name='Facebook page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='flickr_link',
            field=models.URLField(blank=True, help_text='Url to a flickr page, will be displayed                     under a small logo.', null=True, verbose_name='Flickr page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='gplus_link',
            field=models.URLField(blank=True, help_text='Url to a google plus page, will be displayed                     under a small logo.', null=True, verbose_name='Google plus page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='insta_link',
            field=models.URLField(blank=True, help_text='Url to a instagram page, will be displayed                     under a small logo.', null=True, verbose_name='Instagram page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='pinterest_link',
            field=models.URLField(blank=True, help_text='Url to a pinterest page, will be displayed                     under a small logo.', null=True, verbose_name='Pinterest page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='px500_link',
            field=models.URLField(blank=True, help_text='Url to a 500px page, will be displayed                     under a small logo.', null=True, verbose_name='500px page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Url to a twitter page, will be displayed                     under a small logo.', null=True, verbose_name='Twitter page link'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='vk_link',
            field=models.URLField(blank=True, help_text='Url to a vkontakte page, will be displayed                     under a small logo.', null=True, verbose_name='Vkontakte page link'),
        ),
    ]
