# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_conf_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='google_site_verification_id',
            field=models.CharField(blank=True, help_text='Enter her your google site verification ID,                     it will be displayed in <meta name="google-site-verification" />                     in phiroom\'s headers.', max_length=254, null=True, verbose_name='Your google site verification ID.'),
        ),
    ]
