# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_conf_google_site_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='piwik_analytics_id',
            field=models.CharField(blank=True, help_text='Enter here you piwik analytics ID to start tracking.', max_length=254, null=True, verbose_name='Your piwik analytics ID.'),
        ),
    ]
