# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_auto_20160710_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='piwik_analytics_id',
        ),
        migrations.AddField(
            model_name='conf',
            name='piwik_analytics_site_id',
            field=models.CharField(blank=True, help_text='Enter here you piwik analytics site ID to start tracking.', max_length=254, null=True, verbose_name='Your piwik analytics site ID.'),
        ),
        migrations.AddField(
            model_name='conf',
            name='piwik_analytics_url',
            field=models.CharField(blank=True, help_text='Enter here you piwik analytics url (without leading                     and trailing slashes "/").', max_length=2000, null=True, verbose_name='Your piwik analytics url.'),
        ),
    ]
