# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_auto_20150614_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='conf',
            name='home_page',
        ),
        migrations.AddField(
            model_name='conf',
            name='abstract_delimiter',
            field=models.CharField(default='[...]', help_text='Characters sequence used to separate abstract part of a                     weblog post.', max_length=254, verbose_name='Abstract delimiter'),
        ),
        migrations.AddField(
            model_name='conf',
            name='abstract_last_char',
            field=models.CharField(default='…', help_text='Characters sequence added at the end of each abstract, in                     replacement of the abstract delimiter.', max_length=254, verbose_name='Abstract last character'),
        ),
        migrations.AddField(
            model_name='conf',
            name='abstract_replaced_chars',
            field=models.CharField(default=',.!?…', help_text='List of characters that will be replaced by abstract last                     character if they end abstract.', max_length=254, verbose_name='Abstract replaced chararcters'),
        ),
        migrations.AddField(
            model_name='conf',
            name='insta_link',
            field=models.URLField(blank=True, help_text='Url to a instagram page, will be displayed on                     under a small logo.', null=True, verbose_name='Instagram page link'),
        ),
        migrations.AddField(
            model_name='conf',
            name='pinterest_link',
            field=models.URLField(blank=True, help_text='Url to a pinterest page, will be displayed on                     under a small logo.', null=True, verbose_name='Pinterest page link'),
        ),
        migrations.AddField(
            model_name='conf',
            name='px500_link',
            field=models.URLField(blank=True, help_text='Url to a 500px page, will be displayed on                     under a small logo.', null=True, verbose_name='500px page link'),
        ),
        migrations.AddField(
            model_name='conf',
            name='slideshow_duration',
            field=models.PositiveIntegerField(default=3000, help_text="Duration between 2\xa0slides in portfolio's                     carousel, in milliseconds.", verbose_name='Carousel slideshow duration'),
        ),
    ]
