# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_auto_20160301_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='librairy_logo',
            field=models.ImageField(blank=True, default='images/default/librairy_default_logo.svg', help_text='The logo you can see on librairy page header.                     Idealy 50px height.                     Leave blank to use default one.', null=True, upload_to='images/logos/', verbose_name="Librairy's logo."),
        ),
        migrations.AlterField(
            model_name='conf',
            name='weblog_logo',
            field=models.ImageField(blank=True, default='images/default/default_logo.svg', help_text="The logo you can see on each weblog's page header.                     Leave blank to use default one.", null=True, upload_to='images/logos/', verbose_name="Weblog's logo."),
        ),
    ]
