# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_conf_activate_weblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='activate_contact',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate contact page.', verbose_name='Activate contact page'),
        ),
        migrations.AddField(
            model_name='conf',
            name='contact_title',
            field=models.CharField(default='Contact', help_text='Contact page title (default to "Contact"', max_length=254, verbose_name='Contact page title'),
        ),
        migrations.AddField(
            model_name='conf',
            name='weblog_slug',
            field=models.CharField(default='contact', max_length=270),
        ),
        migrations.AddField(
            model_name='conf',
            name='weblog_title',
            field=models.CharField(default='Weblog', help_text='Weblog title (default to "Weblog"', max_length=254, verbose_name='Weblog title'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='activate_weblog',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate weblog.', verbose_name='Activate weblog'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='n_posts_per_page',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of posts per list page on weblog.', verbose_name='Paginate by'),
        ),
    ]
