# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0008_auto_20171008_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='contact_slug',
            field=models.CharField(default='contact', max_length=270),
        ),
        migrations.AlterField(
            model_name='conf',
            name='weblog_slug',
            field=models.CharField(default='weblog', max_length=270),
        ),
    ]
